### PR TITLE
add tests and adjust test workflow

### PR DESCRIPTION
**Pull request by mmulholla**
add test and adjust test worklfow. Needed for release build to work.

### CODE REVIEW

**Review by tisutisu — COMMENTED** [review]
I think `test.yaml` changes only needed in this stage repo. Do we require the tests in the stage repo? As we discussed  as part of story https://issues.redhat.com/browse/HELM-395 we have not included tests in the stage repo.

**Comment by mmulholla** [comment]
Yes, I think we overlooked the release requirement in the previous issue. At the moment we are inconsistent, we copy the test.yml file so in runs for a release but then the tests do not exist so it fails. So we have a choice - do not copy test.ymal so a workflow release in stage doe snot run any tests, or copy the tests so it does.  I went with the latter as we do not want to accidentally break the stage repo.

**Comment by tisutisu** [comment]
> Yes, I think we overlooked the release requirement in the previous issue. At the moment we are inconsistent, we copy the test.yml file so in runs for a release but then the tests do not exist so it fails. So we have a choice - do not copy test.ymal so a workflow release in stage does not run any tests, or copy the tests so it does. I went with the latter as we do not want to accidentally break the stage repo.

Okay got it.. now we have to enable the "tests" directory from development to charts repo.

**Review by tisutisu — APPROVED** [review]
LGTM

**Pull request merged**
